[tool.poetry]
name = "skysim"
version = "0.1.0"
description = ""
authors = ["taiwithers <59430904+taiwithers@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.2"
matplotlib = "^3.10.0"
astropy = "^7.0.1"
astroquery = "^0.4.9.post1"
jupyter = "^1.1.1"
pydantic = "^2.10.6"
timezonefinder = "^6.5.8"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"
pandas = "^2.2.3"
ipydatagrid = "^1.4.0"
pylint = "^3.3.4"
black = "^25.1.0"
nbqa = "^1.9.1"
pyright = "^1.1.394"
mypy = "^1.15.0"
pre-commit = "^4.1.0"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
follow_untyped_imports = true
disallow_any_unimported = true
disallow_any_expr = false
disallow_any_decorated = true
disallow_any_explicit = false
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = false
disallow_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
disable_error_code = ["attr-defined"]

[tool.pylint]
disable = ["no-member"]
