[image]
pixels = 250
width = 4
height = 4.5
filename = "SkySim"
fps = 2.5
dpi = 200

# the different colours to be interpolated between as the sky background
# the times at which these colours appear is defined in
# image.sky-colours-index-by-time
sky-colours = ["#000", "#171726", "dodgerblue", "#00BFFF", "lightskyblue"]

# the different maximum magnitude values determining which objects are visible
# these values are interpolated between in the same manner as image.sky-colours
# the times corresponding to these magnitudes are defined in
# image.magnitude-values-index-by-time
magnitude-values = [6, 4, 2, 0, -1.5]

# =============================================================================

[image.sky-colours-index-by-time]
# hour [float] = index [int]
# index is the zero-counted index of sky-colours
# 13.5 : 2 would set the 1:30pm sky colour to be the 3rd entry in image.sky-colours
0 = 0
3 = 1
5 = 2
7 = 3
12 = 4
15 = 3
18 = 2
21 = 1
24 = 0

[image.magnitude-values-index-by-time]
# hour [float] = index [int]
# index is the zero-counted index of magnitude-values
# 13.5 : 2 would set the 1:30pm maximum magnitude to be the 3rd entry in
# image.magnitude_values
0 = 0
3 = 1
5 = 2
7 = 3
12 = 4
15 = 3
18 = 2
21 = 1
24 = 0

# =============================================================================

[image.object-colours]
fallback = "white"
# spectral types
O = "lightskyblue"
B = "lightcyan"
A = "white"
F = "lemonchiffon"
G = "yellow"
K = "orange"
M = "lightpink"
# planets
mercury = "white"
venus = "lemonchiffon"
mars = "orange"
jupiter = "white"
saturn = "white"
uranus = "white"
neptune = "white"
