
name: Build & publish docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # let gh actions bot write to the repo
    permissions:
      contents: write

    steps:

      # Checkout your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # set up python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # install just
      - uses: extractions/setup-just@v2 # from just readme

      # install ffmpeg
      - name: Install ffmpeg
        run: |
          sudo apt update # per gh recommendation
          sudo apt install ffmpeg

      # install python-based dependencies
      - name: Install python dependencies
        run: |
          pip install -r docs/source/requirements.txt
          pip install --editable git+https://github.com/taiwithers/SkySim.git

      # run sphinx
      - name: Build docs with sphinx
        run: just full-build-docs

      # deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
